services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend/react-typescript/
      dockerfile: Dockerfile.frontend
    ports:
      - "81:80"
    depends_on:
      - database
    networks:
      - internet
      - localnet

  backend:
    container_name: backend
    build:
      context: ./Backend/
      dockerfile: Dockerfile.backend
    ports:
      - "7777:7777"
    depends_on:
      - database
    networks:
      - localnet

  database:
      env_file: "database.env"
      container_name: database
      build:
        context: ./MySQL/
        dockerfile: Dockerfile.database
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "3306:3306"
      networks:
        - localnet

  streamserver:
    container_name: streamserver
    build:
      context: ./StreamServer/
      dockerfile: Dockerfile.streamserver
    ports:
      - "4444:4444"
    depends_on:
      - database
    networks:
      - internet
      - localnet
    volumes:
      - "videos:/var/lib/docker/volumes/videos/_data"

  nginxserver:
      container_name: nginxserver
      build:
        context: ./NginxServer/
        dockerfile: Dockerfile.nginxserver
      ports:
        - "88:87"
      depends_on:
        - database
      networks:
        - internet
        - localnet
      volumes:
      - "videos:/var/lib/docker/volumes/videos/_data"

volumes:
  videos:

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge